### ISSUE TITLE
retro-stats-cli has problems with some ROM names?!

### ISSUE THREAD

**Issue by jedcooper** [langest/RetroStats#1]
I dunno what was updated/upgraded. What I can say is it wasn't apt upgrade. 
But since yesterday my retro-stats-cli isn't working anymore. I did another git pull and (re-)installed again. The problem consists.
```
$ retro-stats-cli
Traceback (most recent call last):
  File "/home/pi/.local/bin/retro-stats-cli", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/stats/main.py", line 94, in main
    log = Log(args.file)
  File "/home/pi/.local/lib/python3.7/site-packages/stats/log.py", line 21, in __init__
    for row in rows:
  File "/usr/lib/python3.7/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
```
EDIT:
OK deletion of game_stats.log didn't fix the issue. But filling it with a single game from scratch did.
My old backupped .log file is 415k in size then throws the same error again. So it's not usable for me anymore.
I upload it to my personal pastebin for debugging purpose. Here: http://fb.retrohd.de/BUCklj8/

**Comment by jedcooper** [comment]
OK, I've fixed it by removing a line with some "illegal" characters of `NUL` (Notepad++) resp. `@^@^` etc. (Linux nano) in the .log file.
Not sure how they've got there though.

**Comment by StonedEdge** [comment]
@jedcooper  Did you ever get this fixed? I am seeing the same issue. 

pi@retropie:~/RetroPie/RetroStats/stats $ retro-stats-cli -c total -b 20 -n 3 -c times
  File "/home/pi/.local/lib/python3.7/site-packages/stats/main.py", line 94, in main
    log = Log(args.file)
  File "/home/pi/.local/lib/python3.7/site-packages/stats/log.py", line 21, in __init__
    for row in rows:
  File "/usr/lib/python3.7/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
-bash: pi@retropie:~/RetroPie/RetroStats/stats: No such file or directory

**Comment by langest** [comment]
Hi, sorry about the lack of replies. It was a long time since I did anything in this repo.

@jedcooper Glad it worked out.
@StonedEdge It looks like you are passing `-c` argument twice. I don't think that will work. Probably need to run either one, depending on how you want the stats to aggregate.
Also, the error you are getting is hinting that you are missing the stats file. By default the script expects the file to be located at `/home/pi/RetroPie/game_stats.log`. But you can override this with the `-f` flag if you have a file named something else, somewhere else.
